# Generated by Django 3.1.5 on 2021-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operador', models.IntegerField(default=0)),
                ('nombre_operador', models.CharField(max_length=200)),
            ],
        ),
    ]
