# Generated by Django 3.1.5 on 2021-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_beneficiado', models.CharField(max_length=10)),
                ('nombres_beneficiado', models.CharField(max_length=200)),
                ('apellidos_beneficiado', models.CharField(max_length=200)),
                ('email_beneficiado', models.CharField(max_length=200)),
                ('usuario_operador', models.CharField(max_length=10)),
            ],
        ),
    ]
