# Generated by Django 3.1.5 on 2021-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiado',
            name='usuario_operador',
            field=models.CharField(max_length=200),
        ),
    ]
