# Generated by Django 3.1.5 on 2021-01-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210121_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='cod_med',
            new_name='medicamento',
        ),
    ]
