# Generated by Django 3.1.5 on 2021-01-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20210121_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='medicamento',
            new_name='cod_med',
        ),
    ]
