# Generated by Django 3.1.5 on 2021-01-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0003_auto_20210121_1508'),
        ('inventario', '0006_auto_20210121_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cod_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamento.medicamento'),
        ),
    ]
