# Generated by Django 3.1.5 on 2021-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_beneficiado', models.CharField(max_length=10)),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('cod_med', models.CharField(max_length=10)),
                ('cant_entrega', models.IntegerField(default=0)),
            ],
        ),
    ]
