# Generated by Django 3.1.5 on 2021-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='benefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneefactor', models.IntegerField(default=0)),
                ('nombre_benefactor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='beneficiado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiado', models.IntegerField(default=0)),
                ('nombre_beneficiado', models.CharField(max_length=200)),
                ('email_beneficiado', models.CharField(max_length=200)),
                ('id_operador', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_beneficiado', models.IntegerField(default=0)),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de entrega')),
                ('id_med', models.IntegerField(default=0)),
                ('cant_entrega', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='grupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=200)),
                ('leyenda_grupo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_benefactor', models.IntegerField(default=0)),
                ('fecha_recibido', models.DateTimeField(verbose_name='Fecha de recibido')),
                ('id_med', models.IntegerField(default=0)),
                ('cant_ingreso', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='laboratorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lab', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_med', models.IntegerField(default=0)),
                ('principio_activo_med', models.CharField(max_length=200)),
                ('nombre_comercial_med', models.CharField(max_length=200)),
                ('nombre_laboratorio_med', models.CharField(max_length=200)),
                ('presentación_med', models.CharField(max_length=200)),
                ('dosis_med', models.CharField(max_length=200)),
                ('via_admon_med', models.CharField(max_length=200)),
                ('grupo_med', models.CharField(max_length=200)),
                ('subgrupo_med', models.CharField(max_length=200)),
                ('fecha_vencimiento_med', models.DateTimeField(verbose_name='Fecha de vencimiento')),
            ],
        ),
        migrations.CreateModel(
            name='operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operador', models.IntegerField(default=0)),
                ('nombre_operador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subgrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subgrupo', models.CharField(max_length=200)),
            ],
        ),
    ]
