# Generated by Django 3.1.5 on 2021-01-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='benefactor',
        ),
        migrations.DeleteModel(
            name='beneficiado',
        ),
        migrations.DeleteModel(
            name='entrega',
        ),
        migrations.DeleteModel(
            name='grupos',
        ),
        migrations.DeleteModel(
            name='ingreso',
        ),
        migrations.DeleteModel(
            name='inventario',
        ),
        migrations.DeleteModel(
            name='laboratorios',
        ),
        migrations.DeleteModel(
            name='operador',
        ),
        migrations.DeleteModel(
            name='subgrupos',
        ),
    ]
