# Generated by Django 3.1.5 on 2021-01-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamento', '0002_auto_20210121_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='id_med',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='cod_med',
            field=models.CharField(default='', max_length=10),
        ),
    ]
