# Generated by Django 3.1.5 on 2021-01-21 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
        ('grupo', '0001_initial'),
        ('subgrupo', '0001_initial'),
        ('medicamento', '0003_auto_20210121_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='nombre_laboratorio_med',
        ),
        migrations.AddField(
            model_name='medicamento',
            name='nombre_lab_med',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='grupo_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupo.grupo'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='subgrupo_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subgrupo.subgrupo'),
        ),
    ]
